### ISSUE TITLE
Kick.com integration?

### ISSUE THREAD

**Issue by SamirNazim** [jlplenio/crude-twitch-viewer-bot#102]
Is it possible to integrate this with Kick.com? Does Kick not require proxies?

**Desktop (please complete the following information):**
 - CTVBot version: [e.g. 0.4.0]
 - Windows version: [e.g. 10]

**Describe the bug**

**Screenshots**

**logs**
If applicable, post the part of the ctvbot.log, that refers to the problem.

**Comment by jlplenio** [comment]
#89
