### ISSUE TITLE
trouble opening on Mac OS

### ISSUE THREAD

**Issue by dirtydan808** [jlplenio/crude-twitch-viewer-bot#103]
disclaimer, I'm super new to this kind of stuff. I just can't figure out how to open the program up! I've for sure formatted my proxies correctly, and I've put a terminal window at the folder and typed in ls Like I see in the screenshots, but I can't get further. Sorry I'm a noob, and any help is greatly appreciated!!!

**Comment by jlplenio** [comment]
Please report the screenshot.
