### ISSUE TITLE
Release .exe is faster than unpacked code.

### ISSUE THREAD

**Issue by AngelMarchena** [jlplenio/crude-twitch-viewer-bot#121]
**Desktop (please complete the following information):**
 - CTVBot version: [e.g. 0.4.0] v0.5.1
 - Windows version: [e.g. 10] Window Server 2019 Datacenter

**Describe the bug**
If the code is executed in IDE (Visual Studio Code, IDLE) it suffers significant performance issues. The released .exe is drastically faster. Can we get documentation on how the .exe is compiled to get that performance improvement? 

**Screenshots**

**logs**
If applicable, post the part of the ctvbot.log, that refers to the problem.

**Comment by jlplenio** [comment]
That is quite the unique behavior. Maybe the IDE hooks into the program and slows it down?
I never had slowdowns in the IDE, mine is PyCharm Pro.
Have you tried running the main_guy.py directly without the IDE?

The executable is built via pyinstaller, see https://github.com/jlplenio/crude-twitch-viewer-bot/blob/45c0de9650855f66ed5e623b3b918ca8a360c5fa/.github/workflows/build_release.yml#L47

**Comment by jlplenio** [comment]
Quite strange. Maybe try running a different Python version? 
If you use poetry and my lock file, you can recreate my dev environment exactly.
