### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by rickjames1337** [jlplenio/crude-twitch-viewer-bot#122]
Compatibility for Opera GX or any other chromium browsers that use less resources compared to using google chrome if possible. I'm not sure if it is possible to do that but it would probably help the usage of RAM and CPU for the machine.

**Comment by rickjames1337** [comment]
@jlplenio

**Comment by jlplenio** [comment]
The problem is that Chrome and Firefox work best to not get detected as bots. Playwright seems not to support your suggestions currently: https://github.com/microsoft/playwright/issues/20915

**Comment by rickjames1337** [comment]
is it possible to get firefox compatibility because firefox is a bit better
on cpu usage as well im trying to use it on a lower end machine haha
