### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by User0102030405** [jlplenio/crude-twitch-viewer-bot#125]
Hi there. How to spawn more than 3 bots. 
![12](https://user-images.githubusercontent.com/132748120/236616437-80ce8087-030c-48f7-a871-7c3b71c5aace.PNG)

**Comment by jlplenio** [comment]
Can you press the "Spawn 3 instances" button again? And what OS are you running?

**Comment by User0102030405** [comment]
> Can you press the "Spawn 3 instances" button again? And what OS are you running?

I try it so many times. I try it on windows 10 and now on ubuntu . Its same. Only 3 . I have premium proxy form webshare

**Comment by User0102030405** [comment]
im idiot......everything work fine. Sorry :(

**Comment by jlplenio** [comment]
Happy to heat that it works for you!
