### ISSUE TITLE
Issue opening instances

### ISSUE THREAD

**Issue by rickjames1337** [jlplenio/crude-twitch-viewer-bot#126]
Yes I've looked over the troubleshooting guide.

**Desktop (please complete the following information):**
 - CTVBot version: [e.g. 0.4.0] CTVBot v0.5.1
 - Windows version: [e.g. 10] Win 10

**Describe the bug**
A clear and concise description of what the bug is. (When trying to create a viewer the instance is immediatly terminated. When the headless feature is turned off to doesn't even get passed the "about:blank" page and terms. I've been using this for awhile and the link is correct. Love the work by the way.

**Screenshots**
If applicable, add screenshots to help explain your problem. (https://imgur.com/a/dlm73BJ)

**logs**
If applicable, post the part of the ctvbot.log, that refers to the problem. In screenshot provided.

**Comment by jlplenio** [comment]
Please try without proxies, i.e. empty proxy_list.txt

**Comment by rickjames1337** [comment]
Ah yeah it worked probably just bad proxies then?

**Comment by jlplenio** [comment]
Another user reported he had to refresh the proxies in the webshare dashboard.

**Comment by HrvckRacer29** [comment]
Issue still happens even after refreshing. It works fine for a hot minute then dies out again. I know I can only refresh my proxies 9 times a month so not feasible to do it everytime it dies so I just stopped using the program.

**Comment by jlplenio** [comment]
Can you check for errors in the dashboard under Stats -> Error?

**Comment by HrvckRacer29** [comment]
target_read_idle_timeout

**Comment by jlplenio** [comment]
This issue is new to me. I will try on my side. Does anyone have the same problem?

**Comment by ricardopereirasilveira** [comment]
> This issue is new to me. I will try on my side. Does anyone have the same problem?

hello man, yes, i have the same issue with the linux application too. I can share the logs if you need.
thank you.

**Comment by jlplenio** [comment]
Please do or send me via mail.

**Comment by ricardopereirasilveira** [comment]
> Please do or send me via mail.

sent, thank you.

**Comment by jlplenio** [comment]
ToDo: Add version and system info to log start.

**Comment by jlplenio** [comment]
I added the feature that each connection is tried three times. This could mitigate the problem, but only if the problem lies with CTVBot.
Please download the latest version: https://github.com/jlplenio/crude-twitch-viewer-bot/releases/latest

**Comment by ricardopereirasilveira** [comment]
ill try now, return soon with feedback :D

**Comment by ricardopereirasilveira** [comment]
I'm still having many problems, I'll report them below.

OS: Linux
Version: 0.5.3
Ubuntu Linux VPS with XRDP
Proxy: WebShare.io
Running for more than 13h

1. CTVBot is not opening more than 20 instances, when reaching the 20th instance it seems to give timeOut and only opens new ones, when old ones are closed. This version seems to be less unstable than the previous one (0.5.2)

2. When leaving 20 instances active, after 13 hours running it closed all instances and did not reopen them.

3. CTVBot is having trouble opening and most of the time it giv
[ctvbot.log](https://github.com/jlplenio/crude-twitch-viewer-bot/files/11604412/ctvbot.log)
es Timeout.

4. CTVBot is closing repeatedly, after some open instances, it closes completely and it is necessary to open everything again.

log is attached, substitute my login part for XXXXX to hide this information as the LOG is here on github.

**Comment by jlplenio** [comment]
Hmmm I cannot recreate it. I tried for an hour with stable cpu, ram, traffic and 100 viewers at 160p. 
![grafik](https://github.com/jlplenio/crude-twitch-viewer-bot/assets/16845311/6b24c0ec-d63a-44ab-8ece-4a5f2655776d)

**Comment by AnonBit** [comment]
@ricardopereirasilveira 13h was online your stream ?
I think to resolve this problem, is required to start and stop instances using API based if stream is online or offline.
PS. I know @jlplenio don't want this to prevent commercialization of bot

**Comment by jlplenio** [comment]
Reopen if the problem reoccurs.
