### ISSUE TITLE
have error code for windows and not starting at all

### ISSUE THREAD

**Issue by MEZO1038** [jlplenio/crude-twitch-viewer-bot#136]
**Please answers the following questions:**
- CTVBot version? [e.g. 0.4.0]
- OS with version? [e.g. Windows 10, Ubuntu 20.04]
- Streaming platform? [e.g. twitch.tv, kick.com, youtube.com]
- Proxies from webshare.io? [yes, no] 

**Describe the bug**  

**Screenshots**  

**Logs**  
If applicable, post the part of the ctvbot.log, that refers to the problem.

**Comment by jlplenio** [comment]
Please open a new issue with a more detailed problem description, i.e. answer the template questions!
