### ISSUE TITLE
bots do not raiding

### ISSUE THREAD

**Issue by coderunnerxd** [jlplenio/crude-twitch-viewer-bot#138]
bots do not raid the destination channel. 

its a bug? 

there's a possibility?

**Comment by Grillekkj** [comment]
CVTB cannot participate in raids, as it does not yet have the twitch login function and raids need the user to be logged in

**Comment by jlplenio** [comment]
@Grillekkj that is what I am hearing. I don't really watch Twitch :) @coderunnerxd I will update #40 when the login feature is integrated.
