### ISSUE TITLE
Looks like Twitch is only allowing logged in accounts

### ISSUE THREAD

**Issue by l3franc3** [jlplenio/crude-twitch-viewer-bot#142]
Hi all!

First of all, I have to say that I've been following this project since its first version and been using it without any issue, using webshare proxies. You're doing a great job jlplenio!

I've noticed since today, that instances keep in yellow and never go to green, so view does not count on stream. I've checked my proxies, renew them, check bandwitdh and everything looks fine.

When I launch an instance in headful mode, I can see how the app takes me to the final Twitch link and opens everything in theater mode, but video doesn't play. If you check the console, a lot of Graph errors show up, with a Playback Auth error that I've never seen before.

A few weeks ago I dag into making a custom version of the app, and I was able to log in using the auth code, injecting it in the browser using Firefow in PW. It kind of worked, but sometimes the instances didn't log in correctly, and it happened randomly. So I decided to leave it there and wait for the official version with the login users tab.

So today, when I noticed instances were not working, I tried again with my "custom" app with the auth codes and I noticed that only when Firefox logs in, the view is counted and the video showed.

I'm so sorry for the long text! xDD 
But I wanted to know if anyone else noticed the instances not working.

Once again, this project is amazing and you're doing a great job!!

xXx

**Comment by 1234Testaccount123** [comment]
Yeah I tried everything so far

**Comment by l3franc3** [comment]
Are you having the same issue?
Instances staying in yellow?

**Comment by 1234Testaccount123** [comment]
exact same. Was working perfectly yesterday

**Comment by ricardopereirasilveira** [comment]
same behavior for me.

**Comment by l3franc3** [comment]
Looks like Twitch is starting to check with GraphQL if the user is logged in to count the view and play the video

**Comment by Grillekkj** [comment]
same issue here

**Comment by jlplenio** [comment]
It is really nice to see how you help each other. Big kudos to all of you.
Since "we" are on the crude path with Playwright, the problem should be fixable. I had working Playwright settings in a local branch for the login implementation that play nice with GraphQL/kasada. Currently, I am at a conference, I will check within 48h if my settings are still working.

**Comment by AnonBit** [comment]
same thing

[GraphQL] One or more GraphQL errors were detected on request 01H1V314JQ7MQP79QPPFB15DR0. PlaybackAccessToken: failed integrity check [{…}]
[GraphQL] One or more GraphQL errors were detected on request 01H1V315JBXTYYATKPPQCHZHJE. ChatRoomBanStatus: unauthenticated

**Comment by l3franc3** [comment]
> It is really nice to see how you help each other. Big kudos to all of you. Since "we" are on the crude path with Playwright, the problem should be fixable. I had working Playwright settings in a local branch for the login implementation that play nice with GraphQL/kasada. Currently, I am at a conference, I will check within 48h if my settings are still working.

In case it helps, those are the cookies I am injecting to make it work with Firefox, extracted from a txt previously created:

`self.context.add_cookies([{ "name":"auth-token", "value":nextToken, "path":"/", "domain":".twitch.tv" }])
 self.context.add_cookies([{ "name":"last_login", "value":"2023-04-23T15:28:12Z", "path":"/", "domain":".twitch.tv" }])
 self.context.add_cookies([{ "name":"name", "value":nextUser, "path":"/", "domain":".twitch.tv" }])`

I also check if the user is logged in, with this line (to switch color from green to purple):

`check_if_logged = self.page.evaluate("window.localStorage.getItem('video_ads.stream_loudness');")`

Hope it helps! @jlplenio

**Comment by lnzh1** [comment]
It's working again! Without having made any kind of change. Already get the squares in green!!!!

**Comment by jlplenio** [comment]
Thank you @lnzh1. I away and cannot confirm myself, but as others have reported, it looks like they rolled back their aggressive checks and it does continue to work https://github.com/streamlink/streamlink/issues/5370#issuecomment-1572823986.

**Comment by jlplenio** [comment]
As they suggest in the issue above, this may have been advance notice of the actual introduction of this restriction. Lets see.

**Comment by jimminylubbox** [comment]
Might be a good idea to roll out the account feature asap then

**Comment by l3franc3** [comment]
People say that was a little warning, and they will activate this restriction permanently soon.
So it would be AWESOME to have a new version with the users login tab implemented.

Thank you so much for your work @jlplenio!
