### ISSUE TITLE
About the recent Twitch issue

### ISSUE THREAD

**Issue by MRSSSMR** [jlplenio/crude-twitch-viewer-bot#144]
Hello, I'm always using it well
A few days ago, due to a recent algorithm change
only a yellow mark appeared on the proxy, but it didn't work properly

Just wondering if you have a project in store 
in case the proxy doesn't work properly!!

Thank you for always working hard

**Comment by Grillekkj** [comment]
#142

**Comment by jlplenio** [comment]
Thank you, @Grillekkj, I have additional settings ready, if they reimplement the changes.
