### ISSUE TITLE
Webshare Bandwidth quickly consumed

### ISSUE THREAD

**Issue by SRZIsHere** [jlplenio/crude-twitch-viewer-bot#146]
**Please answer the following questions:**
- CTVBot version? [e.g. 0.4.0] 0.5.3
- OS with version? [e.g. Windows 10, Ubuntu 20.04] Windows 11
- Streaming platform? [e.g. twitch.tv, kick.com, youtube.com] Twitch.tv
- Proxies from webshare.io? [yes, no]  yes (the 10 Free ones)

**Describe the bug**  
The bandwith is consumed in 10 minuts for 1 GB

Also, quick question for the subscription plans, if we buy a plans with 100 Proxies, it means that in the best scenarios, we will reach a maximum of 100 Viewers ?

Thank you !

**Comment by jlplenio** [comment]
If your stream only offers source quality, e.g. 1080p, then the bandwidth is very high.
With the minimum plan, some viewers may not be counted, the optimum will count all, see here:
https://github.com/jlplenio/crude-twitch-viewer-bot/wiki/Webshare.io-Proxies-Guide
