### ISSUE TITLE
Replace post/get requests with head/option requests

### ISSUE THREAD

**Issue by jlplenio** [jlplenio/crude-twitch-viewer-bot#16]
Intercept and replace requests on the fly to save bandwidth/workload.
Could and should result in crashing the video player :/

**Comment by jlplenio** [comment]
https://playwright.dev/python/docs/network#modify-requests

**Comment by jlplenio** [comment]
I tried it with 20 instances, 10 of which received a "network error 2000" and the other 10 buffered indefinitely. Those that were buffered still counted as viewers even though they consumed almost no bandwidth.
It remains a worthwhile idea to pursue in the future. Although I like the hardware and bandwidth limitations of the tool to naturally limit the potential for abuse and commercialization.

**Comment by jlplenio** [comment]
some day.

**Comment by DrinkingJoe** [comment]
May I ask, what exactly did you change in the requests?

**Comment by jlplenio** [comment]
The answer is in the issue title. And implemented with this:

> https://playwright.dev/python/docs/network#modify-requests

Good luck.
