### ISSUE TITLE
HI this bug happened to me alot 

### ISSUE THREAD

**Issue by Migren2009** [jlplenio/crude-twitch-viewer-bot#172]
CTVBot version? . 0.6.0]
OS with version? [ Windows 10, ]
Streaming platform? [e.g. twitch.tv]
Proxies from webshare.io? [yes]
TWITCH Instance 30 died: TimeoutError:Timeout 20000ms exceeded.... Please see ctvbot.log

**Comment by Grillekkj** [comment]
i think u did it wrong

**Comment by Migren2009** [comment]
- CTVBot version? . 0.6.0]
- OS with version? [ Windows 10, ]
- Streaming platform? [e.g. twitch.tv]
- Proxies from webshare.io? [yes] 
TWITCH Instance 30 died: TimeoutError:Timeout 20000ms exceeded.... Please see ctvbot.log

**Comment by jimminylubbox** [comment]
A lot of instances are being detected as bots, I'd just wait for a fix

**Comment by jlplenio** [comment]
Twitch should work perfectly. Please post your logs @Migren2009 and I will take a look.

**Comment by Migren2009** [comment]
it was from my internet

**Comment by jlplenio** [comment]
Thank you for letting us know. Enjoy.
