### ISSUE TITLE
TWITCH Instance 12 died: Error:net::ERR_TUNNEL_CONNECTIO... Please see ctvbot.log.

### ISSUE THREAD

**Issue by Santino0910** [jlplenio/crude-twitch-viewer-bot#180]
**Please answer the following questions:**
- CTVBot version?  0.6.1
- OS with version? Windows 11
- Streaming platform? twitch.tv,
- Proxies from webshare.io? yes, private proxy

**Describe the bug**  
I can't get past 12 or 15 instances that start to die

**Logs**  
TWITCH Instance 12 died: Error:net::ERR_TUNNEL_CONNECTIO... Please see ctvbot.log.

**Comment by jlplenio** [comment]
Hey @Santino0910. 
The ERR_TUNNEL_CONNECTION_FAILED error indicates that there is a problem with your proxies.
Maybe it reached the maximum traffic or bandwidth or threads/concurrency.

You can always test with an empty proxy_list.txt whether the general function works.

**Comment by squeaks1811** [comment]
im getting the exact same thing but none of mine work and i just purchased the 100 proxies from the website recommended

**Comment by yomiyo17** [comment]
Same here

**Comment by Cloudstrifeff7** [comment]
I have this problem too. I did not exceed the maximum traffic or bandwidth or threads/currency.

**Comment by jlplenio** [comment]
hey @squeaks1811, please send me your logs via mail and I will look into it. Webshare proxies should always work!

**Comment by squeaks1811** [comment]
> hey @squeaks1811, please send me your logs via mail and I will look into it. Webshare proxies should always work!

whats the mail?

**Comment by Dubzie** [comment]
I'm getting the same issue, with Webshare proxies, same proxy's work in another app.

**Comment by djrexy** [comment]
what anoth

> I'm getting the same issue, with Webshare proxies, same proxy's work in another app."

what another application are you using?

**Comment by jlplenio** [comment]
Hello @Dubzie. TimeoutError could indicate that either your system or traffic are at capacity.
On how many instances does this error occur, and what is your CPU/RAM at that time?
If the stream you are watching only allows for source quality, e.g., 1080p60, this also eats a lot of traffic.
This could max out your home internet bandwidth and or the bandwidth/concurrency from the proxy package.

**Comment by AnumalyFuan** [comment]
hello, i get the same issue. it was working really fine used 10 instances smoothly. but suddenly all the instances died and now i can't even use 1 instance

**Comment by Dubzie** [comment]
> Hello @Dubzie. TimeoutError could indicate that either your system or traffic are at capacity. On how many instances does this error occur, and what is your CPU/RAM at that time? If the stream you are watching only allows for source quality, e.g., 1080p60, this also eats a lot of traffic. This could max out your home internet bandwidth and or the bandwidth/concurrency from the proxy package.

That is definitely not the case, I can use those same proxies in a different viewer bot without issue, this one seems to struggle even keeping one connection.
It was working fine for a while then just stopped.

**Comment by Dubzie** [comment]
When I uncheck headless, twitch prompts something about cookies, which i cant click on because the screen gets resized

**Comment by reymaster370** [comment]
> When I uncheck headless, twitch prompts something about cookies, which i cant click on because the screen gets resized

I have the same issue. It seems the cookie notification won't allow you to watch the stream.

**Comment by jlplenio** [comment]
hey @Dubzie and @reymaster370. The cookie banner should not be a problem. If you zoom back via ctrl-, you should see the screen. Did you test with an empty proxy_list.txt whether the general function works?

**Comment by reymaster370** [comment]
> hey @Dubzie and @reymaster370. The cookie banner should not be a problem. If you zoom back via ctrl-, you should see the screen. Did you test with an empty proxy_list.txt whether the general function works?

Hey Jlplenio, I tried it and it works. But I want to try the headless route. Sadly, when I do headless I get this message. TWITCH Instance 1 died: TimeoutError:Timeout 15000ms exceeded.... Please see ctvbot.log. Same thing happens when I do it without headless, and I think its because of the cookie banner.

**Comment by jlplenio** [comment]
Judging by your timeout, he fails here:
https://github.com/jlplenio/crude-twitch-viewer-bot/blob/8380c49fdeba680c202b124c789c72c7d0abaa03/ctvbot/sites.py#L222C1-L222C73

He is reaching the desired website, but does not find the video player? Can you zoom back with ctrl and minus(-) to see beyond the cookie banner and what page/step the instances dies on?

**Comment by Dubzie** [comment]
Even in headless and ctrl- it wont allow me to allow/click accept cookies

In the background, the stream is playing.

**Comment by reymaster370** [comment]
> Judging by your timeout, he fails here: https://github.com/jlplenio/crude-twitch-viewer-bot/blob/8380c49fdeba680c202b124c789c72c7d0abaa03/ctvbot/sites.py#L222C1-L222C73
> 
> He does reach the desired website, but does not find the video player of Twitch? In headful mode, can you zoom back with ctrl and minus(-) to see beyond the cookie banner and check what page/step the instances dies on?

The player does not play at all for some reason.

**Comment by reymaster370** [comment]
Also, when you click cookie and accept it, nothing happens and the window reloads again. I tried it again and it shows the video now, but it still reloads non stop.
