### ISSUE TITLE
Macos Monterey Crash on startup.

### ISSUE THREAD

**Issue by Otooooo** [jlplenio/crude-twitch-viewer-bot#204]
**Please answer the following questions:**
- CTVBot version? [e.g. 0.4.0]   V0.6.1
- OS with version? [e.g. Windows 10, Ubuntu 20.04] macos monterey

**Screenshots**  
<img width="488" alt="Screenshot 2023-09-28 at 19 47 29" src="https://github.com/jlplenio/crude-twitch-viewer-bot/assets/115180163/fa2baed9-cd7e-4de3-9412-8358b79e1cf5">

**Logs**  
If applicable, post the part of the ctvbot.log, that refers to the problem.
[ctvbot.log](https://github.com/jlplenio/crude-twitch-viewer-bot/files/12752458/ctvbot.log)

**Comment by jlplenio** [comment]
I suspect you are running on an Apple Silicon device?
Github doesn't currently offer a native ARM runner, so I cannot build an executable for this architecture.
But if they do in the future, I will easily add ARM-based runners for Raspberry Pi or Apple Silicon.
