### ISSUE TITLE
When a Thread is dead the Node.js App dosent being stoppen from executing

### ISSUE THREAD

**Issue by TwitchAPP** [jlplenio/crude-twitch-viewer-bot#22]
When a thread is dead the Node.js app dosent being stopped from executing also the thread will not be completly stopped.

**Comment by TwitchAPP** [comment]
Dear, for each instance of the browsers is one Node.js application being running. Is it possible that only one Node.js app is needed?

**Comment by jlplenio** [comment]
The new version 0.2.0 should do a better cleanup job.
As synchronous playwright is not thread safe([1](https://github.com/microsoft/playwright-python/issues/470#issuecomment-770621695)), each instance needs its own node.js app.
I will tinker around with an asynchronous playwright implementation, if I find a lot of time.
