### ISSUE TITLE
ModuleNotFoundError: No module named 'tkinter' on Ubuntu 23

### ISSUE THREAD

**Issue by jlplenio** [jlplenio/crude-twitch-viewer-bot#227]
### Discussed in https://github.com/jlplenio/crude-twitch-viewer-bot/discussions/222

<div type='discussions-op-text'>

<sup>Originally posted by **talorno** November 22, 2023</sup>
Traceback (most recent call last):
  File "main_gui.py", line 1, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "ctvbot/gui.py", line 6, in <module>
ModuleNotFoundError: No module named 'tkinter'
[30132] Failed to execute script 'main_gui' due to unhandled exception!

no way to fixing, i installed all the python tk packages, nothing
</div>

**Comment by jlplenio** [comment]
Thank you for bringing this issue to our attention @talorno. There is currently an issue with pyinstaller and I have to try to find a solution that works for macOS, unix and Windows. It is on the top of my ToDo list.

**Comment by bRUNS123** [comment]
same here

**Comment by jlplenio** [comment]
@bRUNS123 @cooldudes9001 Linux should work in the newest pre-release. Please try:
https://github.com/jlplenio/crude-twitch-viewer-bot/releases/tag/v0.6.2
