### ISSUE TITLE
Viewer count no longer increasing

### ISSUE THREAD

**Issue by jnwright** [jlplenio/crude-twitch-viewer-bot#243]
**Please answer the following questions:**
- CTVBot version 0.8.0
- Windows 11
- Twitch
- Webshare proxies

**Describe the bug**  
Viewer count is suddenly not increasing. The chat features work, which means the bots are in the chat, but they're somehow not being counted as viewers. Bot detected also equals false. Screenshots indicate that they are on the stream.

**Comment by jlplenio** [comment]
Do you experience this bug still?
