### ISSUE TITLE
How many proxies are recommended? 

### ISSUE THREAD

**Issue by ForClosed** [jlplenio/crude-twitch-viewer-bot#25]
Like how many would I need from webshare to have a consistent 25 or so viewers

**Comment by jlplenio** [comment]
I believe the lowest number of proxies you can buy is 50, so take 50 and try it out. 
If everything works to your liking, you may need to increase the monthly bandwidth limit.

**Comment by ForClosed** [comment]
Ok thanks. Last question, will I need residential?

**Comment by jlplenio** [comment]
No problem. Honestly:
I work with 50 "Proxy Server" proxies from webshare, with the "High Priority Network" option added.
Never had any problems, so this appears to be sufficient.
