### ISSUE TITLE
URGENT - Webshare blocks proxies

### ISSUE THREAD

**Issue by MarsToyStore** [jlplenio/crude-twitch-viewer-bot#262]
**Please answer the following questions:**
- CTVBot version? 0.8.0 v8
- OS with version? Windows 11
- Streaming platform? Twitch / Kick
- Proxies from webshare.io? Yes 

**Describe the bug**  

Webshare has implemented a new feature called "Activity Meter" 
You can access it via "Settings => Check account". 
This has already been mentioned [here](https://github.com/jlplenio/crude-twitch-viewer-bot/discussions/256#discussioncomment-9172981). 

This is caused by sending requests to `passport.twitch.tv`. If used regularly, the account is blocked and Webshare blocks the use of proxies. 
To the best of my knowledge, I don't think this request is useful (with or without token account). Just use another page to launch the instances, perhaps?

This is a matter of urgency because, without an effective solution, the use of your software will be severely restricted. 
Thank you for your work. 

**Screenshots**  
![Screen 1](https://github.com/jlplenio/crude-twitch-viewer-bot/assets/154351360/3ea55b39-7733-434c-83d9-976f9e78bc36)
<img width="813" alt="Screen 2" src="https://github.com/jlplenio/crude-twitch-viewer-bot/assets/154351360/a7dc758a-e220-444e-a0d5-97fd1766795e">
<img width="821" alt="Screen 3" src="https://github.com/jlplenio/crude-twitch-viewer-bot/assets/154351360/cf3e980c-80b9-4125-9dc5-c85f551122cd">

**Comment by jlplenio** [comment]
Wow. Thank you very much for your detailed information.
1. I will reach out to webshare and ask what this new feature is about.
2. I will change the initial page for twitch, this should reduce these hits.
Strangely, I do not see any calls to passport.twitch.tv when I look at the traffic?!

**Comment by MarsToyStore** [comment]
Thank you for your prompt reply. 
In my traffic page, I can clearly see requests to passport.twitch.tv, and these seem to be the only ones causing problems. 
"Settings" => "Activity Meter" => "Requests to authentication pages" => "View requests". 
It seems like a simple problem to solve if you don't need to send requests to this page, but I don't know.

**Comment by valeriopet** [comment]
is there any news about it? I have 2 blocked subscriptions.

**Comment by jlplenio** [comment]
I reached out to them for comment. Here is an update to reduce auth requests hits on startup and restarts:
https://ko-fi.com/Post/Feature-Preview-v9a--Webshare-fix-G2G6XDSKF

**Comment by naxa420** [comment]
9$😂

**Comment by naxa420** [comment]
> I reached out to them for comment. Here is an update to reduce auth requests hits on startup and restarts:
> 
> https://ko-fi.com/Post/Feature-Preview-v9a--Webshare-fix-G2G6XDSKF

9$😅

**Comment by jlplenio** [comment]
@naxa420 Same fix here: https://github.com/jlplenio/crude-twitch-viewer-bot/releases/tag/v0.6.4

**Comment by valeriopet** [comment]
Has this latest update resolved the problem with webshare?

**Comment by jlplenio** [comment]
Webshare stated that they added the activity meter to detect fraudulent proxy use activity. If such a case is detected, then the user needs to do an ID verification to unblock their proxies. I am in extensive discussion with them.

Two questions to the community:
1. With the newest version, does the tool exceed the webshare activity meter still?
2. Users who have been completely blocked by the combination of CTVBot and Webshare proxies, could you please email me your email address so webshare can investigate these cases?

**Comment by MarsToyStore** [comment]
Hello,

After two weeks of use:

1 - There was a reduction, but unfortunately my account was blocked again. Is it impossible to completely avoid the affected page? Another adjustment to your new version seems necessary. 

2 - It's possible, but do you think Webshare considers this use legitimate? 

Thank you.

**Comment by jlplenio** [comment]
I assume the affected page is needed for all things related to authentication. So I for auth it is mandatory.
I could block all connection attempts to "passport.twitch.tv" for non-auth instance, but this could introduce side-effects.
I am in discussion with webshare. You can send me your email address and I can transmit it to webshare for investigation, if you want.

As there are only a handful of users speaking up, this does not seem too critical.

**Comment by jlplenio** [comment]
I raised the issue and concerns with webshare. They communicated to me, that they will significantly increase the limits of the activity meter. Therefore, this should not trigger normal use with my tool anymore. 🎉
