### ISSUE TITLE
Instant bot detection

### ISSUE THREAD

**Issue by Kokia1** [jlplenio/crude-twitch-viewer-bot#265]
**Please answer the following questions:**
- CTVBot version v9a_FIX_0.8.0
- OS with version? Win 11
- Streaming platform?  twitch
- Proxies from webshare.io? [yes] 

**Describe the bug**  
Since one week twitch instantly detects the bot. Accounts are logged in via tokens.
i regenerated 20 accounts and every bot is detected after 5 minutes. I also renewed my proxylist,

(spawn_instance_thread);sites;todo_after_spawn;Cookie banner is still here - Possible GraphQL error / bot detected, Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

**Comment by jlplenio** [comment]
Are you sure that you use the v9a? As all instance should use the following one user agent.
The only optimization on my side I can offer is for you to try deleting all user-agents in the txt file and only use this single one:
>Mozilla/5.0` (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

**Comment by Kokia1** [comment]
I am running CTVBot_KOFI_v9a_FIX_0.8.0_20240426_Windows-X64 
I try to delete the users and come back to you.
