### ISSUE TITLE
Doesn't go past the "content is intended for certain audiences"

### ISSUE THREAD

**Issue by Bloodjack01** [jlplenio/crude-twitch-viewer-bot#287]
- CTVBot version? 0.6.4 and tested on 0.6.1
- OS with version? Windows 10
- Streaming platform? twitch.tv
- Proxies from webshare.io? Yes

**Describe the bug**  
The app doesn't go past the "Just one second... XXX's content is intended for certain audiences" by itself anymore (headless or not), stays in the Yellow state and is not counted by twitch.

I tested on multiple streams and games to troubleshoot the issue, there are no problems with games intended for everyone or stream without this kind of warning, the instances goes green and are counted by twitch.
No issues with my proxies either.

**Comment by jlplenio** [comment]
Thank you for your report. Sounds like Twitch updated their mature popup and its css:
https://github.com/jlplenio/crude-twitch-viewer-bot/blob/dffd00248ddd5270f66bdc8b71eb84c3a037e970/ctvbot/sites.py#L291

**Comment by BIGS772** [comment]
Same issue here any workaround ?

**Comment by MrAdex77** [comment]
same issue

**Comment by jlplenio** [comment]
I plan to publish a quick fix in 24h.

**Comment by jlplenio** [comment]
I cannot reproduce the error, the current CSS is correct, and my instance successfully clicks the button in the notification to continue.

**Comment by Bloodjack01** [comment]
> I cannot reproduce the error, the current CSS is correct, and my instance successfully clicks the button in the notification to continue.

Can confirm, Strangely enough it seemed to be temporary. Everything is back to normal too on my end.

BUT, as soon as you replied with the CSS hint :

https://github.com/jlplenio/crude-twitch-viewer-bot/blob/dffd00248ddd5270f66bdc8b71eb84c3a037e970/ctvbot/sites.py#L291

I checked it live on my end on the day the issue was still happening and the CSS was correct, no differences between the website and your code. So, even if it was temporary , twitch might have tested something else who was able to break the automation.
Twitch might still have a few card in its sleeves to stop those kind of tools.

In any cases, thanks for your quick reply and reactivity!

**Comment by jlplenio** [comment]
In the far future, I would like to put all the CSS for e.g. mature banner, follow button, cookie banner etc in a unified json file. So that if something changes, the user can make adaption own their own. Or add additional custom CSS that they want to block.
