### ISSUE TITLE
free proxies dont work anymore

### ISSUE THREAD

**Issue by jameslang99** [jlplenio/crude-twitch-viewer-bot#289]
**Please answer the following questions:**
- CTVBot version? 0.6.4
- OS with version? windows 11 latest version as in july 21st
- Streaming platform? twitch
- Proxies from webshare.io? yes the 10 free trial version proxies

**Describe the bug**  
no bot viewers come in using the free proxies trial version. i mean they used to work really well now no viewers come in. Viewer instances are all green but no new bot viewers come. i haven't bought webshare proxies in a while so i dont know if paid proxies have this problem 

**Screenshots**  
If applicable, 
![Screenshot 2024-07-21 223100](https://github.com/user-attachments/assets/1a1d336c-8a99-425b-bd18-9c049211725f)

**Logs**  
If applicable, post the part of the ctvbot.log, that refers to the problem.

**Comment by jlplenio** [comment]
Please check your statistics on webshare. The free proxies only have a limited amount of traffic included.
