### ISSUE TITLE
proxies

### ISSUE THREAD

**Issue by Kizuno18** [jlplenio/crude-twitch-viewer-bot#31]
hello!
how did i know if the instances are using the same proxy
or know what proxy the instance are using
and know how many proxies is being used?

**Comment by jlplenio** [comment]
CTVB rotates the proxies. So if you give it 10 proxies and start 11 instances, the 11th instance will use the first proxy again.
Additionally, you can watch the ctvb.log while the program is running to see which instance uses which proxy.
