### ISSUE TITLE
Cant unzip file to make program

### ISSUE THREAD

**Issue by m4od** [jlplenio/crude-twitch-viewer-bot#319]
**Please answer the following questions:**
- CVAmp version? [e.g. 0.4.0]
- OS with version? [e.g. Windows 10, Ubuntu 20.04]
- Streaming platform? [e.g. twitch.tv, kick.com, youtube.com]
- Proxies from webshare.io? [yes, no] 

**Describe the bug**  

**Screenshots**  

**Logs**  
If applicable, post the part of the cvamp.log, that refers to the problem.

**Comment by m4od** [comment]
Something is wrong. Even when downloading the release, the same thing happens. There is no executable.

**Comment by KevinBytesTheDust** [comment]
My bad, it is fixed. Enjoy: https://github.com/KevinBytesTheDust/CVAmp/releases/tag/v0.7.3
