### ISSUE TITLE
having problems getting this to run

### ISSUE THREAD

**Issue by Mrfrosty724** [jlplenio/crude-twitch-viewer-bot#35]
having problems getting this to run have proxys but wont run as a exe am i doing something wrong
but i am also new to this github if anyone can help would mean alot thank you

**Comment by jlplenio** [comment]
@Mrfrosty724 Please be more specific, what exactly is not working? Is there any information in the ctvb.log?

**Comment by jlplenio** [comment]
Please take a look at the [troubleshooting wiki](https://github.com/jlplenio/crude-twitch-viewer-bot/wiki/Troubleshooting).
You are welcome to reopen this issue, if you have further questions.
