### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by thekingx7** [jlplenio/crude-twitch-viewer-bot#42]
i can add proxy list with out username and passpord only ip and port?

**Comment by jlplenio** [comment]
Please see #26.

**Comment by thekingx7** [comment]
i see but idk what i do ?
edit file proxy or what 

sorry i take your time

**Comment by thekingx7** [comment]
i can add link bigo live?

**Comment by jlplenio** [comment]
For bigo please use this more advance tool:
