### ISSUE TITLE
Way to bot viewers without consuming large amounts of internet bandwidth.

### ISSUE THREAD

**Issue by DrinkingJoe** [jlplenio/crude-twitch-viewer-bot#46]
I just wanted to let you know that there is a way to bot viewers without consuming internet bandwidth.  
If you cause error #3000: error while decoding video, the browser instance still counts as a viewer while not receiving any stream and consuming minimal amounts of bandwidth.  
Also wanted to let you know that the ability to add your own botting accounts would be extremely useful.
Thanks

**Comment by Lucifer192192** [comment]
Can you tell me which URL it is? How can he make 3000 error

**Comment by Lucifer192192** [comment]
There was a network error. Please try again. (Error #2000)
All I could find was #2000
I can't find #3000

**Comment by Lucifer192192** [comment]
******/v1/segment/****
I will prevent this URL from reaching the #2000 error
But it seems that after a while the viewer will decrease

**Comment by Lucifer192192** [comment]
> 
Thank you very much for your help

**Comment by Lucifer192192** [comment]
As soon as I open Headless, the viewer doesn't increase
I don't understand why

**Comment by Lucifer192192** [comment]
I'm looking for ways to do this without eating up Internet bandwidth

**Comment by jlplenio** [comment]
I will look into this. As stated in #16 I had similar plans.
