### ISSUE TITLE
about feature

### ISSUE THREAD

**Issue by Kizuno18** [jlplenio/crude-twitch-viewer-bot#50]
hello, thanks for answearing about tokens login, yes you said that will add acc/pw instead, but think again about tokens :P

well, here i would to ask you to add referer's integration
that we can add in txt's like this

**Comment by jlplenio** [comment]
Can you point me to the Twitch docs which token to use to authenticate a browser instance with Twitch?

**Comment by jlplenio** [comment]
#40.
