### ISSUE TITLE
About proxy

### ISSUE THREAD

**Issue by CupcakeUkrain** [jlplenio/crude-twitch-viewer-bot#51]
I had 1.000 free proxies(live) and 25 private. Can i use free proxies?

**Comment by jlplenio** [comment]
You certainly can try your free proxies. Just be sure to check whether the viewer count increases.

**Comment by CupcakeUkrain** [comment]
but how i can add this free proxy? txt file "proxy.txt" want a username and password, if this data is not entered, then the code does not see these proxies...

**Comment by jlplenio** [comment]
Please try the format `ip:port::`
