### ISSUE TITLE
cant open websites with embedded twitch stream

### ISSUE THREAD

**Issue by iryandydanish** [jlplenio/crude-twitch-viewer-bot#53]
I have a website that I have embedded my twitch stream. I cant seem to get the instance to run as it instantly dies.

**Comment by jlplenio** [comment]
The bot expects to arrive at a Twitch website to 1. verify that everything is working, and 2. use buttons and keyboard shortcuts to select settings and full-screen mode. For this reason, an embedded screen does not work and is not supported.
