### ISSUE TITLE
Proxy without username and password 

### ISSUE THREAD

**Issue by OpenSourceSimon** [jlplenio/crude-twitch-viewer-bot#54]
This code is only functional with proxies that require a username and password. Some proxies work without credentials, therefore it would be nice if a better way of getting the credentials would be implemented. I'm thinking of opening a pull request for this, but I first need to read some documentation about proxies.

**Comment by jlplenio** [comment]
Please try in this format.
https://github.com/jlplenio/crude-twitch-viewer-bot/issues/51#issuecomment-1286754834
