### ISSUE TITLE
Instances turns back to yellow after a period of time

### ISSUE THREAD

**Issue by ukaam1337** [jlplenio/crude-twitch-viewer-bot#55]
Hello, 

First of all thanks for your software, it's really simple and really good to use ! 

I've followed every instructions and, in addition with the 10 free proxies given when you create an account on WebShare, I've bought 50 Private Proxies in the country I live (and countries around) 

I started a stream and decided to "spam" a bit the "Create 3 Instances" to see a bit and I realised that everything is working fine with viewer bot turning "Green" on your software, but after a certain amount of time, these instances turns back to Yellow. 
Creating other instances is possible but as someone mention it in another thread here, after a time, even if instances are killed, there is still a bit memory usage. 

I'm using a pretty recent but very normal laptop, and sometimes, the ram if I create let's say 50~ instances is almost 95% usage. Would that explain that ? And if yes, what would be the optimal Ram % of usage not to exceed ? And if it's not the Ram usage, what is it ? Is it normal for instances to turn back to yellow after a certain time ? 

Thanks again for your work and your time
- Sarah

**Comment by RasperSquee** [comment]
I believe there is a memory leak that needs to be fixed. The RAM will slowly climb up overtime before it reaches 99% and the program crashes, causing your instances to all die. I just end the process in command prompt (Taskkill /IM CTVB_0.2.0_20220804.EXE /F) and open it again. I have a macro that repeatedly does this for me.

**Comment by ukaam1337** [comment]
Hello, 

Thanks for your reply ! 

Well, yesterday I tried something : creating slowly instances after 3 by 3, letting them turn green each time and making sure to never exceed 90% of ram usage. It worked. 

But let's talk a bit about the number before I buy new RAM : I could only get ~100 instances with a 32Gb computer (not the laptop). Is this number "ok" ? Should I have to think of getting new RAM if I wanted more ?

**Comment by jlplenio** [comment]
Thank you both for your thorough reports. As the title of the tool suggests, this is a "crude" solution of a viewer bot. Which means there is no intricate or advanced method to manipulation twitch to again viewer. This tool simply spams chrome instances and actively watches the stream. That is in itself very inefficient and resource intensive. Your reported instances count of 100 is excellent (I am guessing 160p was available). My machine starts to struggle there too.

I will analyze the memory leak when I find time.
I might also implement having a Chrome instance watch in 2-3 tabs, each with a different proxy.
Both should reduce bulk.

**Comment by ukaam1337** [comment]
Thanks for your reply ! Yeah yeah, I totally get it. What do you think about service like : streamerviewerbot(dot)com ? Don't you think they use exactly the same method but on way more powerful servers than our machines ? I'm just curious. 

Also, do you think that buying some more RAM is a smart moove ?

It's the second time I see you talking about the "160p options". What does that exactly mean ? It means that the twitch channel offer that possibility and the launched instance is set to choose that option ? Or is it something I need to activate manually ? (Ps : All the 100 instances were launched headless)

**Comment by jlplenio** [comment]
I do not know this service. Could be that they use the same solution, maybe something more elegant.
In any case, not on a Windows machine, this alone saves a large number of resources.

When the twitch channel you selected offers the 160p option, the bot will use it and save resources.
If only 720p or 1080p is available, this costs plenty of resources.

Memory leak addressed in #48.
