### ISSUE TITLE
problem with a lauch

### ISSUE THREAD

**Issue by simbaO** [jlplenio/crude-twitch-viewer-bot#59]
Hello if i lauch the .py he is instantaly closed i need ur help please

**Comment by jlplenio** [comment]
Don't start the .py. 

Download this:
https://github.com/jlplenio/crude-twitch-viewer-bot/releases/download/v0.3.0/CTVB_0.3.0_20221107.zip

And follow these instructions:
https://github.com/jlplenio/crude-twitch-viewer-bot/wiki/Detailed-Tutorial

**Comment by simbaO** [comment]
thanks u bro
