### ISSUE TITLE
ERR_TUNNEL_CONNECTION_FAILED

### ISSUE THREAD

**Issue by wsoulless** [jlplenio/crude-twitch-viewer-bot#63]
**Desktop (please complete the following information):**
 - CTVB version: 0.3.1
 - Windows version: 10

**Describe the bug**
I'm using the 10 proxies from webshare.
All looks good but when I open any istance I got an error (see log details).

**logs**
============================================================
Traceback (most recent call last):
  File "instance.py", line 87, in start
  File "instance.py", line 161, in spawn_page
  File "playwright\sync_api\_generated.py", line 8114, in goto
  File "playwright\_impl\_sync_base.py", line 104, in _sync
  File "playwright\_impl\_page.py", line 495, in goto
  File "playwright\_impl\_frame.py", line 146, in goto
  File "playwright\_impl\_connection.py", line 43, in send
  File "playwright\_impl\_connection.py", line 396, in wrap_api_call
  File "playwright\_impl\_connection.py", line 78, in inner_send
playwright._impl._api_types.Error: net::ERR_TUNNEL_CONNECTION_FAILED at https://www.twitch.tv/login
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================

**Comment by jlplenio** [comment]
Hmm. That is a rare one. Can you:
1. Try without proxies, i.e. an empty proxy_list.txt. Does it work?
2. Try to update your Chrome browser to the newest version.
3. Check at the beginning of the log, if your instances "take" the correct proxies, e.g.:
`INFO;Thread-2;instance;spawn_page; STARTINGinstance 1, proxy http://123.345.678.213:6998` **<--**

**Comment by b31ver** [comment]
same problem

**Comment by jlplenio** [comment]
> same problem

Please follow the steps above so I can diagnose the problem.

**Comment by wsoulless** [comment]
> > same problem
> 
> Please follow the steps above so I can diagnose the problem.

Without proxies I believe it works? Or at least the chrome sessions stays alive and it doesn't shut down after few seconds.

**Comment by alexferra** [comment]
same issue

**Comment by jlplenio** [comment]
Can you check for errors in [webshare.io](https://www.webshare.io/?referral_code=w6nfvip4qp3g).   
Maybe the free proxies of webshare have a concurrency limit, which you are hitting.
![grafik](https://user-images.githubusercontent.com/16845311/204479761-7ba82777-a065-47da-9022-0441caf49281.png)
