### ISSUE TITLE
Free proxies without auth are not working

### ISSUE THREAD

**Issue by alexferra** [jlplenio/crude-twitch-viewer-bot#64]
not reading proxy file

**Comment by jlplenio** [comment]
Please describe your problem in more detail.

**Comment by UnepistacheGit** [comment]
sad thing, we can only use proxy's from Webshare.io. others aren't working

**Comment by alexferra** [comment]
it just doesn't work.  I figured to read proxies without a pass one must add :: , but it simply does not work

**Comment by jlplenio** [comment]
> sad thing, we can only use proxy's from Webshare.io. others aren't working

That is not correct. Please tell me which proxy provider you are using, and I will try it myself.

> it just doesn't work. I figured to read proxies without a pass one must add :: , but it simply does not work
Is the "Proxies available"-counter increasing? And if so, what error do you get when you spawn instances?

**Comment by alexferra** [comment]
Yes the counter is increasing. here are some proxies:

this website has proxies that work:

https://freeapiproxies.azurewebsites.net/


error logs:
![image](https://user-images.githubusercontent.com/14792671/204402636-b7ba881a-4f41-4df0-9a9f-80045125c392.png)


135.181.29.13:3128::
54.175.197.235:80::
155.138.197.162:80::
138.68.75.207:80::
124.13.181.4:80::
194.35.127.130:80::
212.107.28.122:80::
23.238.33.186:80::
80.48.119.28:8080::
41.188.149.77:80::
100.20.101.185:80::
134.209.189.42:80::
15.235.150.136:80::
209.146.104.51:80::
104.148.36.10:80::
65.21.48.92:8888::
76.72.138.48:3128::
42.3.182.146:80::
172.104.91.25:80::
54.75.75.45:8888::
110.164.3.7:8888::
44.211.92.188:80::
217.160.50.205:80::
209.146.105.244:80::
103.16.128.221:80::
83.229.72.174:80::
103.174.102.127:80::
154.26.134.214:80::
209.182.239.62:80::
185.191.76.84:80::
143.244.134.24:80::
46.171.75.186:80::
139.99.237.62:80::
165.154.243.247:80::
118.185.179.10:80::
83.229.73.175:80::
165.154.236.248:80::
178.63.133.25:80::
51.15.242.202:8888::
185.216.116.18:80::
198.49.68.80:80::
49.0.2.242:8090::
8.210.83.33:80::
20.194.219.228:80::
80.252.5.34:7001::
89.38.98.236:80::
203.198.207.253:80::
81.174.11.159:61743::
164.70.122.6:3128::
34.81.72.31:80::
100.20.122.18:80::
89.107.197.165:3128::
66.29.154.103:3128::
104.244.75.218:8080::
83.220.47.146:8080::
198.167.193.71:8118::
167.235.21.123:10076::
87.247.186.105:80::
200.32.51.179:8080::
198.59.191.234:8080::
185.61.152.137:8080::
46.0.203.186:8080::
212.145.210.146:80::
194.106.16.41:80::
212.230.172.6:80::
41.188.149.79:80::
117.54.114.103:80::
149.202.168.208:80::
116.58.229.130:23500::
118.172.187.127:8080::
177.82.85.209:3128::
91.209.11.132:80::
116.80.41.12:80::
58.27.59.249:80::
165.3.122.6:80::
103.148.192.83:8082::
188.17.117.126:3128::
103.106.193.117:7532::
85.10.199.48:80::
94.103.85.88:9300::
85.25.198.20:5566::
134.122.58.174:80::
67.61.208.109:80::
5.161.144.91:8080::
124.13.181.7:80::
68.183.58.145:5566::
91.249.134.148:80::
85.25.195.36:8646::
77.73.241.154:80::
68.185.57.66:80::
66.191.31.158:80::
65.37.106.2:80::
54.36.26.122:80::
52.53.251.113:3128::
51.38.191.151:80::
50.239.72.19:80::
50.239.72.18:80::
50.239.72.17:80::
50.239.72.16:80::
50.231.110.26:80::
50.230.222.202:80::
50.227.121.39:80::
50.227.121.38:80::
50.227.121.34:80::
50.227.121.32:80::
50.226.53.178:80::
50.220.187.9:80::
50.220.187.14:80::
50.220.187.11:80::
50.206.25.104:80::
45.79.110.81:80::
24.95.253.39:80::
213.143.113.82:80::
209.37.250.19:80::
190.58.248.86:80::
188.166.56.246:80::
187.130.139.197:8080::
162.0.226.218:80::
158.58.173.147:80::
185.51.10.19:80::
112.120.41.171:80::
52.172.249.189:8080::
140.227.25.191:23456::
103.84.159.8:80::
43.204.16.38:80::
96.232.166.51:80::
31.166.187.248:9812::
105.19.63.217:9812::
41.188.149.75:80::
216.137.184.253:80::
130.185.104.34:3128::
121.1.41.162:111::
201.238.248.139:9229::
212.50.36.89:8083::
161.35.223.141:80::
135.125.216.93:80::
5.1.92.132:80::
201.217.49.2:80::
194.195.120.99:80::
181.113.225.178:80::
172.105.216.60:443::
167.99.236.14:80::
1.32.59.217:47045::
202.6.233.133:80::
1.224.3.122:3888::
47.90.126.78:8118::
41.188.149.73:80::
41.60.235.91:8080::
162.144.236.128:80::
117.54.114.100:80::
117.54.114.101:80::
117.54.114.97:80::
66.29.156.100:80::
123.240.60.64:8888::
94.127.219.99:8080::
109.86.182.203:3128::
142.93.219.22:8080::
41.188.149.78:80::
103.152.112.145:80::
202.158.76.142:2121::
121.139.171.23:80::
174.94.227.20:80::
41.188.149.76:80::
129.194.10.160:80::
178.208.66.243:3128::
91.150.189.122:30389::
178.32.101.200:80::
51.68.140.229:8080::
153.122.86.46:80::
168.119.53.93:80::
89.58.39.225:80::
104.248.90.212:80::
190.82.105.123:43949::
173.212.247.75:80::
136.243.134.87:80::
91.134.136.29:9000::
74.205.128.200:80::
47.56.69.11:8000::
3.39.250.229:80::
204.185.204.64:8080::
197.243.20.186:80::
154.19.187.251:3128::
121.139.171.51:80::
103.20.204.104:80::
100.20.156.53:80::
117.54.114.96:80::
54.211.109.92:80::
188.240.192.92:8090::
41.65.160.171:1981::
93.177.229.164:9812::
35.203.0.3:80::
89.218.5.110:37717::
104.225.220.233:80::
117.54.114.99:80::
213.32.75.88:9300::
40.83.102.86:80::
167.114.96.27:9300::
5.104.174.199:23500::
103.121.215.34:43520::
47.91.126.36:2080::
152.44.40.139:5566::
144.24.238.60:8118::
46.101.160.223:80::
35.86.232.240:80::
45.79.105.229:80::
138.68.172.40:5566::
143.198.77.180:80::
199.167.138.42:3129::
61.216.156.222:60808::
115.144.8.91:80::
195.140.225.11:8111::
221.132.28.18:8090::
52.88.105.39:80::
116.202.209.248:8118::
34.223.105.122:80::
118.26.110.48:8080::
95.0.84.26:80::
72.170.220.17:8080::
3.109.85.109:80::
173.212.195.139:80::
12.218.209.130:53281::
179.184.165.181:8080::
79.111.13.155:50625::
185.231.223.28:3128::
5.9.112.247:3128::
152.204.128.46:33047::
205.201.49.186:53281::
178.218.43.60:4411::
193.161.215.20:8080::
124.158.182.34:7654::
161.117.89.36:8888::
202.62.84.210:53281::
34.236.43.123:80::
129.159.88.228:80::
80.179.140.189:80::
43.255.113.232:85::
103.159.195.9:80::
115.243.88.49:80::
140.227.127.228:80::
50.206.25.111:80::
85.26.146.169:80::
50.206.25.109:80::
50.206.25.106:80::
50.206.25.110:80::
50.206.25.108:80::
24.129.240.222:80::
50.218.57.69:80::
50.217.22.108:80::
50.218.57.70:80::
50.228.83.226:80::
50.228.141.98:80::
50.228.141.102:80::
50.218.57.74:80::
50.217.22.104:80::
50.217.22.111:80::
50.218.57.71:80::
50.228.141.96:80::
50.228.141.99:80::
50.218.57.68:80::
50.217.22.107:80::
50.218.57.65:80::
50.217.22.114:80::
50.217.22.105:80::
50.218.57.67:80::
50.217.22.106:80::
50.217.22.110:80::
50.174.26.60:80::
50.237.89.167:80::
50.227.121.33:80::
50.217.226.40:80::
68.188.59.198:80::
50.220.168.134:80::
24.158.29.166:80::
194.158.203.14:80::
50.237.89.160:80::
41.65.236.43:1981::
198.27.74.6:9300::
52.71.94.225:80::
106.107.203.151:80::
87.248.129.11:3128::
80.249.187.85:8080::
20.187.167.218:80::
145.239.94.39:80::
181.205.106.106:9812::
178.210.51.118:8080::
64.227.23.88:8118::
5.39.62.110:80::
3.133.109.52:80::
89.188.221.47:80::
35.247.150.115:8443::
50.18.70.79:80::
76.164.52.98:80::
85.60.193.39:55443::
167.71.230.124:8080::
155.93.93.68:8080::
54.156.145.160:8080::
139.180.222.158:80::
211.42.155.210:80::
211.42.155.225:80::
142.11.222.22:80::
178.128.156.76:3128::
196.1.95.117:80::
4.227.226.59:1080::
137.184.61.11:8081::
121.139.171.41:80::
34.142.186.45:80::
135.12.203.238:3128::
41.162.52.11:8080::
85.25.199.50:5566::
51.79.41.132:10019::
181.129.43.3:8080::
93.153.95.186:56603::
186.137.169.148:8080::
51.79.41.132:10034::
118.97.235.234:8080::
139.162.8.96:80::
211.42.155.232:80::
167.99.124.118:80::
159.65.129.62:8081::
43.255.113.232:8083::
128.199.13.74:80::
3.111.208.135:80::
135.12.193.146:3128::
135.12.203.188:3128::
43.255.113.232:8085::
51.79.41.132:10068::
135.12.205.35:3128::
135.12.201.148:3128::
135.12.196.97:3128::
135.12.199.88:3128::
196.1.97.209:80::
155.138.132.50:80::
213.230.97.98:3128::
158.69.71.245:9300::
20.187.77.5:80::
18.229.116.13:80::
128.199.97.42:80::
14.139.242.7:80::
13.126.92.209:80::
158.69.27.94:9300::
159.138.152.248:80::
146.59.199.12:80::
173.212.219.228:80::
119.93.129.34:80::
47.87.183.45:8080::
91.209.11.131:80::
186.208.81.214:3129::
65.108.242.241:80::
103.171.44.116:80::
77.68.254.194:8111::
46.38.242.146:80::
45.129.201.238:3128::
13.237.132.198:8080::
185.213.167.97:80::
5.58.110.249:8080::
162.155.10.150:55443::
190.162.91.197:3128::
85.25.246.34:8646::
157.230.122.224:80::
143.110.232.177:80::
54.36.239.180:5000::
213.230.107.235:8080::
167.99.174.59:80::
43.229.72.192:8000::
135.12.200.98:3128::
135.12.194.127:3128::
61.29.96.146:8000::
103.168.29.228:9812::
66.85.30.138:80::
135.12.202.132:3128::
94.130.223.13:3128::
213.242.252.137:3128::
135.12.192.111:3128::
18.228.17.79:80::
23.94.143.167:80::
85.25.1.10:8646::
31.44.89.65:8080::
206.189.146.13:8080::
162.19.50.37:80::
41.65.236.43:1976::
202.61.204.51:80::
164.132.170.100:80::
135.12.196.209:3128::
140.82.1.202:80::
195.231.86.98:80::
117.54.114.32:80::
52.200.191.158:80::
201.238.248.134:443::
151.248.117.248:80::
51.75.206.209:80::
194.67.91.153:80::
117.54.114.35:80::
92.207.253.226:38157::
92.119.59.241:80::
194.124.37.150:8888::
178.150.148.38:8282::
141.95.122.232:80::
212.50.36.69:8083::
176.192.70.58:8005::
138.91.159.185:80::
178.62.92.133:80::
176.100.13.15:8080::
54.86.198.153:80::
203.150.113.90:57322::
52.157.88.150:80::
200.170.175.142:8081::
138.68.235.51:80::
188.72.82.107:8118::
155.4.244.218:80::
85.196.179.34:8080::
103.66.196.218:23500::
104.254.246.152:80::
104.215.127.197:80::
161.35.161.38:80::
64.227.106.157:80::
104.211.157.219:80::
65.21.131.27:80::
3.1.248.232:80::
94.242.55.10:80::
185.218.125.70:80::
208.109.191.161:80::
125.99.58.110:3128::

**Comment by jlplenio** [comment]
@alexferra Thank you for your report. As you are using freely available proxies, I cannot help further.
Even if some appear to be working (10% of your list, I checked), they can load a single website at most.
No free proxy will sustain a load of ~5 Mbits to continously watch an entire stream, that is too expensive for any provider.
I will clarify in the docs and wiki, that free proxies will not work and are not supported. 
You will need to buy proxies, [https://www.webshare.io](https://www.webshare.io/?referral_code=w6nfvip4qp3g) or any other provider to your liking.
