### ISSUE TITLE
Linux executable

### ISSUE THREAD

**Issue by nidark** [jlplenio/crude-twitch-viewer-bot#65]
Hello,
Great work on the project!

I see this in done in phyton. Can we run it from a linux machine ?

**Comment by jlplenio** [comment]
I only support the GUI version. I can try to create a GUI version for Linux.
If you want to run it headless, i.e. without GUI, you have to modify it yourself.

**Comment by nidark** [comment]
Ok, thank you for the answer.
Yeh I meant the GUI version, However is not a request, unless is easy/more wanted / you want etc :)

**Comment by jlplenio** [comment]
I should be able to build it easily via GitHub Actions. The same is true for macOS version #20.
But you have to test it, because I can't :)

**Comment by jlplenio** [comment]
Completely untested and a total shot in the dark. Download the executable here:
https://github.com/jlplenio/crude-twitch-viewer-bot/releases/tag/test_multi_os

**Comment by nidark** [comment]
> Completely untested and a total shot in the dark. Chrome has to be present on the system. Download the executable here: https://github.com/jlplenio/crude-twitch-viewer-bot/releases/tag/test_multi_os
> 
> Feedback welcome, but I cannot promise any support for these versions/OS.

Thank you! Will do a test asap!

**Comment by nidark** [comment]
Ok, This is the result of the first test.
I runed as root, so it should not be an access issue ... 

```
Available proxies 0
Available window locations 20
Traceback (most recent call last):
  File "main_gui.py", line 27, in <module>
  File "gui.py", line 85, in run
  File "tkinter/__init__.py", line 2080, in wm_iconbitmap
_tkinter.TclError: bitmap "/tmp/_MEIq9eExd/ctvb_logo.ico" not defined
[3959] Failed to execute script 'main_gui' due to unhandled exception!
```

**Comment by jlplenio** [comment]
Thank you for testing @nidark. It seems it does find the .ico file, but fails to load it on a unix-like system.
What distro do you use? I can't promise a quick fix, as this is not a priority for me.
https://stackoverflow.com/a/43587905

**Comment by nidark** [comment]
No worries about the speed :). Thank you!
I tested on Ubuntu. 
PS: A dirty way to see will be to eliminate the ico related code just to see if we get into more issues or this is the only one. 
I've seen this quite a few time so is not singular around linux phyton apps: https://tinyurl.com/linuxerr

**Comment by jlplenio** [comment]
Updated. Working, but with misshaped GUI because it is not well coded by me.
https://github.com/jlplenio/crude-twitch-viewer-bot/releases/tag/v0.4.0.unix
