### ISSUE TITLE
Does CTVBot watch advertisements shown on the live stream? 

### ISSUE THREAD

**Issue by Tecktorious** [jlplenio/crude-twitch-viewer-bot#66]
Is it possible for proxies to read the ads ? look even with 50 proxies 0 ads passed

**Comment by RasperSquee** [comment]
ads work youre probably ad banned

**Comment by jlplenio** [comment]
I don't know anything about Twitch ads. CTVBot was built only to temporarily increase viewership.
Thank you, @RasperSquee, for the possbile explanation. I would agree, because CTVBot is simply a controlled Chrome browser.

**Comment by Redox188** [comment]
> ads work youre probably ad banned

can you explain please? i have the same problem

**Comment by RasperSquee** [comment]
If the same IP gets an ad a certain amount of times Twitch will adban that IP. You could also have proxies that don't play ads. Run 10 or more instances in headful to see if you're adbanned, typically in the top left or right it will say commercial break in progress whilst not playing any ads.
