### ISSUE TITLE
Raid Support

### ISSUE THREAD

**Issue by nidark** [jlplenio/crude-twitch-viewer-bot#67]
Hello,
I believe the the bots don't "accept/transfer" the raided channel ?
Is there anything that can be done for this ?

PS: Or maybe the one I tested has over 18 audience, and the bot does not 'click' to accept !?

**Comment by jlplenio** [comment]
CTVBot is nothing more than a dumb Chrome browser. It navigates to the Twitch stream and stays there.
It doesn't click on anything. Even if it followed the raid to the other stream, it would return to the original stream
after the Chrome instance automatically restarts itself after some time.

**Comment by nidark** [comment]
Ok, thanks for the quick answer!
