### ISSUE TITLE
Does CTVBot watch advertisements shown in VODs?

### ISSUE THREAD

**Issue by Redox188** [jlplenio/crude-twitch-viewer-bot#68]
hi, is there a method to use the app like an vod viewer with ads? because the program work with vods but no ads showed.

**Comment by burb7898** [comment]
vods do not display ads, use it on a live stream and when the stream plays ads you'll see them pop up on all the spawned instances.

**Comment by Redox188** [comment]
okay, thank you

**Comment by jlplenio** [comment]
I don't know anything about Twitch ads. CTVBot was built only to temporarily increase viewership.
Thank you very much @burb7898 for your help and explanation. Much appreciated!
