### ISSUE TITLE
Is this working with IPv6 ? 

### ISSUE THREAD

**Issue by hss404** [jlplenio/crude-twitch-viewer-bot#69]
if not would be very nice. i want to buy alot of ipv6. can you tell me if it supports them ?  and if not. can you implement it ?

**Comment by jlplenio** [comment]
Good idea, I will look into this and test an ipv6 implementation.

**Comment by nidark** [comment]
> if not would be very nice. i want to buy alot of ipv6. can you tell me if it supports them ? and if not. can you implement it ?

Good point. I had the same in mind ... :)

**Comment by EmmettF17** [comment]
![изображение](https://user-images.githubusercontent.com/111609341/214176945-c6d7e362-1e80-402c-8574-75733e318771.png)
