### ISSUE TITLE
CTVBot does not select the lowest possible resolution.

### ISSUE THREAD

**Issue by Tecktorious** [jlplenio/crude-twitch-viewer-bot#71]
so i saw you using 32 gb ram and a 12 core cpu i think with 120 pages open ? 
well i tried with 8 core and yet i get only 30 pages open ! does that mean the 166p wont work? 
can u double verified the resolution checker ?

**Comment by jlplenio** [comment]
Disable headless mode and verify yourself which video quality was selected.
If there is only source (e.g., 1080p, 720p) available, CTVBot cannot choose anything lower.

**Comment by Tecktorious** [comment]
i have 166p enabled tho wont  select it ! goes 360p for some reason

**Comment by jlplenio** [comment]
Thank you for your investigation. I will definitely look into it!

**Comment by jlplenio** [comment]
I cannot reproduce this error. Anyone else with the problem of @Tecktorious ?
