### ISSUE TITLE
CTVBot MacOS –  Feedback

### ISSUE THREAD

**Issue by kiloking** [jlplenio/crude-twitch-viewer-bot#75]
CTVB App macOS version not working at OS Ventura 13.0.1
Please Check, If you can, Thanks

**Comment by jlplenio** [comment]
Thank you for testing. Can you post the error message from the ctvbot.log?
If it is emtpy, try to start the tool from the Terminal and post its error message.

**Comment by kiloking** [comment]
Double click the package not run,
and I have not idea, how to start the program by Terminal.
https://imgur.com/5i1AGP2.jpg

**Comment by EduardoArtioli** [comment]
Same thing here

**Comment by EduardoArtioli** [comment]
in case you want to remote connect, im down to try, maybe i can help on development.
add me on discord: snst#2800
i can give you acess to a macos

**Comment by jlplenio** [comment]
Updated. Functional on Ubuntu. Somebody try on macOS:
https://github.com/jlplenio/crude-twitch-viewer-bot/releases/tag/v0.4.0.unix

**Comment by EduardoArtioli** [comment]
Tested on a MacBook Pro
Chip, Apple M1 Pro
macOS, Ventura 13.0.1

<img width="524" alt="Screenshot 2023-01-14 at 18 41 39" src="https://user-images.githubusercontent.com/14796036/212498273-72144bf6-cdc7-47c7-b725-83c18ce8589e.png">

**Comment by jlplenio** [comment]
Can you open a terminal in the folder and execute the file this way?

![grafik](https://user-images.githubusercontent.com/16845311/212498823-902b1128-2d4a-4a52-bf52-b498e87f4318.png)

**Comment by EduardoArtioli** [comment]
made it to run but didn't tested yet

<img width="896" alt="Screenshot 2023-01-16 at 13 32 38" src="https://user-images.githubusercontent.com/14796036/212726754-28a898ff-ee94-466e-b57c-f6d2134562e0.png">

**Comment by jlplenio** [comment]
### Its .... beautiful 🙊

**Comment by jlplenio** [comment]
I'm sure this is due to my rookie GUI coding. I will have to redo it with pack and grid from tkinter, which should scale and adjust dynamically to keep the GUI intact.

**Comment by jnwright** [comment]
the mouse controls on the instances don't work on mac (right to refresh, left to close).

**Comment by jlplenio** [comment]
Thank you for your feedback. Mouse controls should be a macOS issue.
For the instance status boxes, I can imagine that this happens in all version.
I will look into it.

**Comment by jnwright** [comment]
I actually didn't run into the instance box problems on windows! They went away as intended. Maybe it's a GUI thing for mac?

Also sorry if this is documented somewhere else; I can't find it. It seems like all screenshots from people testing macOS have 9 available windows. As a result, I can't spawn more than 9 viewers. How can I increase the number of windows?

**Comment by nthings** [comment]
Getting:
```
[2]    34822 segmentation fault  python main_gui.py
```
when spawning instances on ventura 13.2

**Comment by mrtornado** [comment]
yea same error here on ventura with M2 processor.

/Downloads/CTVBot_Test_0.4.0_20230114_macOS  ./CTVBot_Test_0.4.0_20230114_macOS.bin                     SEGV  took 36s 
./CTVBot_Test_0.4.0_20230114_macOS.bin
Available proxies 310
Available window locations 25
[1]    67172 segmentation fault  ./CTVBot_Test_0.4.0_20230114_macOS.bin

 ~/Dow/CTVBot_Test_0.4.0_20230114_macOS                                                                   SEGV  took 14s

**Comment by jlplenio** [comment]
@mrtornado @nthings My guess is that my executable built on x86-64 is incompatible with the new Apple ARM.

**Comment by jlplenio** [comment]
Further feedback in the discussion please https://github.com/jlplenio/crude-twitch-viewer-bot/discussions
