### ISSUE TITLE
Chrome Issue on Windows 11

### ISSUE THREAD

**Issue by Thenightz** [jlplenio/crude-twitch-viewer-bot#76]
**Desktop (please complete the following information):**
 - CTVBot_0.3.1_20221120
 - Windows version: 11

**Describe the bug**
I spawn the instances and all the browsers display "Your browser encountered an error while decoding the video."
30 out of 50 instances will display this error.

 I tried on different systems and get the same error.

**Screenshots**
![error](https://user-images.githubusercontent.com/121147106/208821285-ed950e57-cd3e-4bd0-a633-43b784e94078.png)

**logs**
If applicable, post the part of the ctvbot.log, that refers to the problem.

N/A

Is there a way to change the browser the bot uses? If so, i tried looking for the tutorial but i couldnt find it.
btw I cleared the cookies for chrome and the cache, I even uninstalled on both systems and when I tried again, I got the same error.

**Comment by jlplenio** [comment]
Never heard of this error code, it seems quite generic. 
I am guessing by "uninstalled", you then installed the newest Chrome version. Which version are you using?
Playwright works with different browsers, but switching away from Chrome is not implemented and will break a lot of functionality.
