### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by Jakee8718** [jlplenio/crude-twitch-viewer-bot#77]
Windows 10 and uhm the viewers simply arent showing up i am using proxies and everything

**Comment by jlplenio** [comment]
What is the status of your [instance boxes](https://github.com/jlplenio/crude-twitch-viewer-bot/wiki/Advanced-features-and-controls#observe-the-status-of-the-instances)?

**Comment by Jakee8718** [comment]
the problem is this 

s\Python39\site-packages\outcome\_impl.py", line 54, in Outcome
    _unwrapped = attr.ib(default=False, eq=False, init=False)
TypeError: attrib() got an unexpected keyword argument 'eq'

**Comment by jlplenio** [comment]
Which release version do you use? https://github.com/jlplenio/crude-twitch-viewer-bot/releases

**Comment by BigForest0001** [comment]
Hi, The programm sees zero proxies in the proxy counter
![Screenshot_5](https://user-images.githubusercontent.com/121899966/210434270-7cc35188-f283-4990-a7c4-56dcd60707ff.png)


I tried different versons of program and different formats in the proxy_list.txt. Even your mockup proxies are not shown in the proxy counter
