### ISSUE TITLE
Hi, The programm sees zero proxies in the proxy counter

### ISSUE THREAD

**Issue by BigForest0001** [jlplenio/crude-twitch-viewer-bot#79]
![Screenshot_5](https://user-images.githubusercontent.com/121899966/210433921-cd32128d-d251-46ae-8687-e740a85ea534.png)
 I tried different versons of program and different formats in the proxy_list.txt. Even your mockup proxies are not shown in the proxy counter

**Comment by EmmettF17** [comment]
IP:PORT:LOGIN:PASS - ✓

IP:PORT - not suitable

**Comment by BigForest0001** [comment]
> IP:PORT:LOGIN:PASS - ✓
> 
> IP:PORT - not suitable

if login and pass for my proxies is none? Should it looks like  this - IP:PORT::

Example of proxy with no  pass and  login 125.15.12.35:2500::

**Comment by jlplenio** [comment]
That is correct, @BigForest0001. If the proxy counter is 0, there is a problem with your proxy_list.txt formatting.
What OS do you use, the GUI in your screenshot looks peculiar?
