### ISSUE TITLE
Further ideas to improve CTVBot.

### ISSUE THREAD

**Issue by EmmettF17** [jlplenio/crude-twitch-viewer-bot#80]
The idea for updating is "crude"!

1. Add a list of twitch accounts, not just one account! 
2. Add the ability to select the number of instances by number, rather than by clicking 1 or 3 instances. For example: I specified 10 instances where a list of 5 twitch accounts is already pre-installed and the program runs 50 instances. 10 copies per 1 twitch account.
3. It is also necessary that the instances are started in turn, and not all at once.
4. 1 instance = 1 proxy server (no proxy server repetitions)
5. It is necessary that the "crude" supports running instances. For example: I specified 15 instances, and 2 of them were closed due to an error, the "crude" itself will restart these 2 instances
6. Do not run the entire page in the browser www.twitch.tv/login but only the player https://player.twitch.tv / which will help reduce the load and allow you to run more instances

**Comment by jlplenio** [comment]
Thank you for your feedback:
1. On it.
2. Won't implement to prevent automating and subsequent commercialization of CTVBot. Therefore, I see it as an advantage, that some user interactions are necessary for operating CTVBot.
4. See 2.
5. Proxies are selected in a circle. Once your e.g. 50 proxies are used up, it selects the first one again. 
    Don't start more than you need if you want no proxy repetitions.
6. See 2.
7. As I am trying to implement a chat functionality, I first want to test to use the chat on the main page. 
    Embedded does not have a chat.

**Comment by EmmettF17** [comment]
For commercialization, programs on http requests are used, not browser emulation(

**Comment by jlplenio** [comment]
Ok.
