### ISSUE TITLE
Can't start any file Windows 11

### ISSUE THREAD

**Issue by altemasse** [jlplenio/crude-twitch-viewer-bot#83]
I put in all my proxis into the list with the correct format.
Downloaded Python and tried to start every single file but nothing happens.
For a break of a second a window pops up, but no GUI or anything.
My system is Windows 11 and i have Chrome installed.
Is there any solution?

**Comment by jlplenio** [comment]
Please try the standalone GUI from here:
https://github.com/jlplenio/crude-twitch-viewer-bot/releases
