### ISSUE TITLE
Timer functionality

### ISSUE THREAD

**Issue by jnwright** [jlplenio/crude-twitch-viewer-bot#88]
First, thank you so much for this tool! It's been super helpful and a cool learning experience.

Are there any thoughts around adding a timer to specific/all instances running? I can think of a few use cases where one would want to set them and forget them.

Thanks!

**Comment by jlplenio** [comment]
You want to start and stop instances via a timer?
If so, I will not implement something like this to prevent automation and subsequent commercialization of CTVBot.
Therefore, I see it as an advantage, that some user interactions are necessary for operating CTVBot.
