### ISSUE TITLE
Add support for other streaming platforms, such as YouTube Live Streaming.

### ISSUE THREAD

**Issue by Bintangelfandri** [jlplenio/crude-twitch-viewer-bot#89]
please modify it a bit, so it can be used for YouTube live streaming too, it's even more interesting if you can for YouTube,

**Comment by jlplenio** [comment]
I did not intend to do that, even if the implementation would be straightforward.
Let's wait for more feedback from the crowd.

**Comment by Bintangelfandri** [comment]
use request method, you will get more live stream view, using selenium it will consume a lot of ram and cpu

**Comment by jlplenio** [comment]
> use request method, you will get more live stream view, using selenium it will consume a lot of ram and cpu

I don't know how to do that. And if I knew, I would say the same, because this technique would be too disruptive.

**Comment by jlplenio** [comment]
I have a modular approach ready, to support multiple streaming platforms, e.g., YouTube.

**Comment by jlplenio** [comment]
Try this version for kick and youtube:
https://github.com/jlplenio/crude-twitch-viewer-bot/releases/tag/v0.5.0

Two problems:
kick: flags and blocks many proxies from webshare with cloudflare
youtube: blocks some of the user-agents saying the browser is outdated

**Comment by Cloudstrifeff7** [comment]
With youtube I have this problem 
![image](https://github.com/jlplenio/crude-twitch-viewer-bot/assets/5221033/1a083ba4-86f4-47ed-a6bc-b86f5df85005)

**Comment by jlplenio** [comment]
Looks like some user-agent caused YouTube to flag the browser as outdated. 
I will have to renew them and update this with try/catch and raise custom error https://github.com/jlplenio/crude-twitch-viewer-bot/blob/beae55b4efa76b9416882186fa11be2e27823449/ctvbot/sites.py#L43
