### ISSUE TITLE
Proxy List Not Reading My Proxies

### ISSUE THREAD

**Issue by AGuyWhoLikesCheese666** [jlplenio/crude-twitch-viewer-bot#93]
I put in a list of proxies and the program is saying I have 0 proxies, these proxies don't have a username or password they're just I.Ps and Ports, I included the list of proxies plus some screen shots of the program saying there's 0 proxies being read.
![1](https://user-images.githubusercontent.com/124258919/216309586-4c4acd4b-2a3e-4f74-8d5c-99092eabc3c5.png)
![2](https://user-images.githubusercontent.com/124258919/216309604-b68400bf-b5cd-46ca-91e6-7265a4d26b3d.png)
![3](https://user-images.githubusercontent.com/124258919/216309613-8432c0cc-97af-49ac-827a-d25e43744e1a.png)
![4](https://user-images.githubusercontent.com/124258919/216309631-6187966b-03d6-439f-887e-fa1f2ee7b7a9.png)

**Comment by jlplenio** [comment]
Please check here: https://github.com/jlplenio/crude-twitch-viewer-bot/wiki/Proxies so that they can be recognised.
If they are public proxies, they will not work as they are too weak for this purpose.
