### ISSUE TITLE
YouTube

### ISSUE THREAD

**Issue by RasperSquee** [jlplenio/crude-twitch-viewer-bot#95]
I tried to use this for YouTube, but it doesn't work because it seemingly needs to detect the twitch player. It works for about 15 seconds before closing itself and showing this in the logs. Could this be changed?

![image](https://user-images.githubusercontent.com/117238356/216975975-ce693934-15eb-4453-bb0c-d262949b1c16.png)

**Comment by jlplenio** [comment]
I could disable such checks like above, to make it work on more websites. 
But this would also other functionality like watching-counters.
#69 duplicate.
