### ISSUE TITLE
Is there any way to reduce the bandwidth usage?

### ISSUE THREAD

**Issue by Mccleinplay** [jlplenio/crude-twitch-viewer-bot#97]
This is my question, since the bandwidth that I contracted (1000gb) will not last long, since testing for 15 minutes consumed me 200mb with only 6 instances.

**Comment by jlplenio** [comment]
The usage sound plausible. As this is a crude solution, you will have to traffic of all running instances.
The only way to reduce the traffic is by only using CTVBot on channels with 160p quality option.
But judging from your traffic, this is already the case. 
You could use CTVBot on a Windows VPS, but this is hugely expensive!
