### ISSUE TITLE
Multiple tabs per browser instance to reduce RAM usage

### ISSUE THREAD

**Issue by nakulwastaken** [jlplenio/crude-twitch-viewer-bot#98]
what if we run all streams in headless mode will it going to count viewership
if not then how can we open many tabs with less ram usage

**Comment by jlplenio** [comment]
Headless count towards viewership. There is an option in Playwright to set a proxy per browser tab.
So, I could potentially restructure CTVBot to have for example 2-3 tabs per browser instance.
Whether and by how much this reduces RAM consumption remains to be seen.

**Comment by jlplenio** [comment]
As of now, this would require a major refactor, which I will not do. I'll keep this suggestion in mind though.
